image: archlinux
packages:
  - nodejs-lts-dubnium
  - npm
sources:
  - https://github.com/justindfuller/hugo-theme
tasks:
  - setup: |
      id
      node -v
      cd hugo-theme-bootstrap4-blog
      npm install 
  - test: |
      cd hugo-theme-bootstrap4-blog
      npm run build
